### ISSUE TITLE
Remove 'form-control-lg' class from control helper default

### ISSUE THREAD

**Issue by franciscohanna92** [KacosPro/bootscake#3]
In line `176` from `BootsCakeFormHelper.php` there's this line:
```php
'templates' => ['input' => '<input type="{{type}}" class="form-control  form-control-lg" name="{{name}}"{{attrs}}/>']
```

I think the `form-control-lg` class should be removed to render the default bootstrap input size

This happens in the last version that gets install with `composer require kacospro/bootscake`

**Comment by KacosPro** [comment]
This should be fixed with a new version, options for size are already there but I need to create a new version 😄 
I haven't had time to create one but I'll do it over the week

Thanks!

**Comment by KacosPro** [comment]
Version 0.0.5 is out, so this should be fixed, BTW @franciscohanna92 if you think anything can be improved PR's are more than welcome, I have big plans for this but I currently I don't have too much time right now
